In [1]:
# Import dependencies
import pandas as pd
import numpy as np
pd.set_option('max_colwidth', 400)

### Extract the crowdfunding.xlsx Data

In [2]:
# Read the data into a Pandas DataFrame
crowdfunding_info_df = pd.read_excel('Resources/crowdfunding.xlsx')
crowdfunding_info_df.head()

,cf_id,contact_id,company_name,blurb,goal,pledged,outcome,backers_count,country,currency,launched_at,deadline,staff_pick,spotlight,category & sub-category
0,147,4661,"Baldwin, Riley and Jackson",Pre-emptive tertiary standardization,100,0,failed,0,CA,CAD,1581573600,1614578400,False,False,food/food trucks
1,1621,3765,Odom Inc,Managed bottom-line architecture,1400,14560,successful,158,US,USD,1611554400,1621918800,False,True,music/rock
2,1812,4187,"Melton, Robinson and Fritz",Function-based leadingedge pricing structure,108400,142523,successful,1425,AU,AUD,1608184800,1640844000,False,False,technology/web
3,2156,4941,"Mcdonald, Gonzalez and Ross",Vision-oriented fresh-thinking conglomeration,4200,2477,failed,24,US,USD,1634792400,1642399200,False,False,music/rock
4,1365,2199,Larson-Little,Proactive foreground core,7600,5265,failed,53,US,USD,1608530400,1629694800,False,False,theater/plays

In [3]:
# Get a brief summary of the crowdfunding_info DataFrame.
crowdfunding_info_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   cf_id                    1000 non-null   int64
 1   contact_id               1000 non-null   int64
 2   company_name             1000 non-null   object
 3   blurb                    1000 non-null   object
 4   goal                     1000 non-null   int64
 5   pledged                  1000 non-null   int64
 6   outcome                  1000 non-null   object
 7   backers_count            1000 non-null   int64
 8   country                  1000 non-null   object
 9   currency                 1000 non-null   object
 10  launched_at              1000 non-null   int64
 11  deadline                 1000 non-null   int64
 12  staff_pick               1000 non-null   bool
 13  spotlight                1000 non-null   bool
 14  category & sub-category  1000 non-null   object
dtypes: bool(2), int64(7), object(6)
memory usage: 103.6+ KB

### Create the Category and Subcategory DataFrames
---
**Create a Category DataFrame that has the following columns:**
- A "category_id" column that is numbered sequential form 1 to the length of the number of unique categories.
- A "category" column that has only the categories.

Export the DataFrame as a `category.csv` CSV file.

**Create a SubCategory DataFrame that has the following columns:**
- A "subcategory_id" column that is numbered sequential form 1 to the length of the number of unique subcategories.
- A "subcategory" column that has only the subcategories. 

Export the DataFrame as a `subcategory.csv` CSV file.

In [4]:
#List the column names
crowdfunding_info_df.columns

Index(['cf_id', 'contact_id', 'company_name', 'blurb', 'goal', 'pledged',
       'outcome', 'backers_count', 'country', 'currency', 'launched_at',
       'deadline', 'staff_pick', 'spotlight', 'category & sub-category'],
      dtype='object')

In [5]:
# Assign the category and subcategory values to category and subcategory columns.
crowdfunding_info_df[['Category','Subcategory']] = crowdfunding_info_df['category & sub-category'].str.split('/',expand=True)
crowdfunding_info_df

,cf_id,contact_id,company_name,blurb,goal,pledged,outcome,backers_count,country,currency,launched_at,deadline,staff_pick,spotlight,category & sub-category,Category,Subcategory
0,147,4661,"Baldwin, Riley and Jackson",Pre-emptive tertiary standardization,100,0,failed,0,CA,CAD,1581573600,1614578400,False,False,food/food trucks,food,food trucks
1,1621,3765,Odom Inc,Managed bottom-line architecture,1400,14560,successful,158,US,USD,1611554400,1621918800,False,True,music/rock,music,rock
2,1812,4187,"Melton, Robinson and Fritz",Function-based leadingedge pricing structure,108400,142523,successful,1425,AU,AUD,1608184800,1640844000,False,False,technology/web,technology,web
3,2156,4941,"Mcdonald, Gonzalez and Ross",Vision-oriented fresh-thinking conglomeration,4200,2477,failed,24,US,USD,1634792400,1642399200,False,False,music/rock,music,rock
4,1365,2199,Larson-Little,Proactive foreground core,7600,5265,failed,53,US,USD,1608530400,1629694800,False,False,theater/plays,theater,plays
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2986,3684,Manning-Hamilton,Vision-oriented scalable definition,97300,153216,successful,2043,US,USD,1609221600,1622350800,False,True,food/food trucks,food,food trucks
996,2031,5784,Butler LLC,Future-proofed upward-trending migration,6600,4814,failed,112,US,USD,1634274000,1638252000,False,False,theater/plays,theater,plays
997,1627,1498,Ball LLC,Right-sized full-range throughput,7600,4603,canceled,139,IT,EUR,1636174800,1639116000,False,False,theater/plays,theater,plays
998,2175,6073,"Taylor, Santiago and Flores",Polarized composite customer loyalty,66600,37823,failed,374,US,USD,1602133200,1618117200,False,True,music/indie rock,music,indie rock
999,1788,4939,"Hernandez, Norton and Kelley",Expanded eco-centric policy,111100,62819,canceled,1122,US,USD,1609308000,1629262800,False,False,food/food trucks,food,food trucks

In [6]:
# Get the unique categories and subcategories in separate lists.
categories = list(crowdfunding_info_df['Category'])
subcategories = list(crowdfunding_info_df['Subcategory'])
print(categories)
print(subcategories)

['food', 'music', 'technology', 'music', 'theater', 'theater', 'film & video', 'theater', 'theater', 'music', 'film & video', 'theater', 'film & video', 'music', 'music', 'technology', 'publishing', 'film & video', 'theater', 'theater', 'film & video', 'theater', 'theater', 'film & video', 'technology', 'games', 'theater', 'music', 'theater', 'film & video', 'film & video', 'games', 'film & video', 'theater', 'film & video', 'film & video', 'theater', 'publishing', 'photography', 'theater', 'technology', 'music', 'food', 'publishing', 'publishing', 'theater', 'music', 'theater', 'theater', 'music', 'music', 'technology', 'theater', 'film & video', 'technology', 'music', 'technology', 'games', 'theater', 'theater', 'theater', 'theater', 'technology', 'theater', 'technology', 'theater', 'theater', 'technology', 'theater', 'theater', 'theater', 'theater', 'film & video', 'music', 'music', 'photography', 'theater', 'film & video', 'publishing', 'theater', 'games', 'music', 'games', 'music', 'technology', 'music', 'theater', 'music', 'publishing', 'theater', 'theater', 'publishing', 'games', 'theater', 'technology', 'film & video', 'theater', 'food', 'games', 'theater', 'theater', 'music', 'technology', 'music', 'music', 'technology', 'theater', 'theater', 'film & video', 'film & video', 'food', 'publishing', 'technology', 'food', 'technology', 'publishing', 'theater', 'film & video', 'photography', 'film & video', 'games', 'games', 'publishing', 'theater', 'photography', 'theater', 'theater', 'theater', 'music', 'food', 'film & video', 'technology', 'theater', 'music', 'film & video', 'theater', 'film & video', 'publishing', 'games', 'technology', 'film & video', 'technology', 'technology', 'music', 'theater', 'technology', 'theater', 'theater', 'technology', 'music', 'music', 'music', 'music', 'theater', 'music', 'theater', 'music', 'photography', 'music', 'theater', 'technology', 'technology', 'music', 'photography', 'theater', 'technology', 'photography', 'theater', 'music', 'film & video', 'music', 'publishing', 'film & video', 'theater', 'technology', 'theater', 'theater', 'theater', 'food', 'theater', 'technology', 'technology', 'theater', 'music', 'theater', 'film & video', 'theater', 'film & video', 'theater', 'theater', 'theater', 'theater', 'music', 'music', 'music', 'music', 'technology', 'film & video', 'music', 'music', 'theater', 'technology', 'food', 'theater', 'music', 'theater', 'publishing', 'music', 'film & video', 'film & video', 'film & video', 'theater', 'theater', 'music', 'music', 'theater', 'theater', 'film & video', 'film & video', 'film & video', 'theater', 'food', 'photography', 'theater', 'film & video', 'music', 'photography', 'games', 'film & video', 'games', 'games', 'theater', 'theater', 'film & video', 'games', 'film & video', 'music', 'film & video', 'theater', 'technology', 'theater', 'publishing', 'music', 'theater', 'theater', 'theater', 'technology', 'publishing', 'games', 'publishing', 'music', 'theater', 'theater', 'film & video', 'publishing', 'music', 'music', 'theater', 'theater', 'photography', 'music', 'music', 'music', 'photography', 'theater', 'theater', 'music', 'theater', 'film & video', 'film & video', 'games', 'photography', 'theater', 'theater', 'theater', 'publishing', 'games', 'theater', 'technology', 'theater', 'film & video', 'theater', 'film & video', 'music', 'technology', 'theater', 'theater', 'music', 'music', 'theater', 'film & video', 'technology', 'food', 'theater', 'theater', 'theater', 'theater', 'theater', 'music', 'food', 'publishing', 'film & video', 'theater', 'music', 'film & video', 'theater', 'theater', 'publishing', 'theater', 'music', 'games', 'theater', 'theater', 'music', 'film & video', 'theater', 'food', 'theater', 'music', 'technology', 'publishing', 'film & video', 'theater', 'film & video', 'theater', 'theater', 'film & video', 'theater', 'music', 'games', 'film & video', 'food', 'technology', 'theater', 'music', 'music', 'music', 'theater', 'theater', 'theater', 'photography', 'music', 'theater', 'theater', 'games', 'film & video', 'music', 'technology', 'food', 'theater', 'music', 'music', 'theater', 'theater', 'film & video', 'technology', 'theater', 'games', 'photography', 'film & video', 'theater', 'theater', 'music', 'music', 'music', 'theater', 'theater', 'theater', 'film & video', 'film & video', 'theater', 'theater', 'film & video', 'theater', 'film & video', 'music', 'music', 'theater', 'film & video', 'theater', 'theater', 'theater', 'photography', 'food', 'film & video', 'publishing', 'theater', 'technology', 'music', 'theater', 'photography', 'publishing', 'technology', 'music', 'film & video', 'theater', 'film & video', 'music', 'film & video', 'music', 'photography', 'theater', 'film & video', 'theater', 'theater', 'theater', 'film & video', 'theater', 'film & video', 'music', 'games', 'theater', 'publishing', 'film & video', 'food', 'theater', 'film & video', 'theater', 'film & video', 'technology', 'theater', 'technology', 'theater', 'food', 'music', 'photography', 'theater', 'theater', 'film & video', 'photography', 'theater', 'theater', 'theater', 'film & video', 'theater', 'theater', 'music', 'film & video', 'theater', 'film & video', 'film & video', 'technology', 'theater', 'theater', 'music', 'theater', 'technology', 'film & video', 'games', 'games', 'film & video', 'music', 'film & video', 'film & video', 'film & video', 'theater', 'music', 'theater', 'theater', 'film & video', 'theater', 'film & video', 'games', 'film & video', 'theater', 'publishing', 'technology', 'technology', 'theater', 'film & video', 'technology', 'food', 'music', 'music', 'film & video', 'publishing', 'publishing', 'film & video', 'technology', 'food', 'photography', 'theater', 'publishing', 'theater', 'food', 'theater', 'publishing', 'theater', 'theater', 'technology', 'journalism', 'food', 'film & video', 'photography', 'technology', 'theater', 'film & video', 'technology', 'technology', 'film & video', 'theater', 'film & video', 'games', 'film & video', 'music', 'publishing', 'theater', 'technology', 'theater', 'theater', 'film & video', 'theater', 'games', 'film & video', 'music', 'theater', 'publishing', 'food', 'film & video', 'music', 'theater', 'film & video', 'film & video', 'film & video', 'theater', 'technology', 'theater', 'film & video', 'music', 'games', 'publishing', 'games', 'theater', 'music', 'film & video', 'theater', 'publishing', 'film & video', 'games', 'food', 'photography', 'games', 'music', 'games', 'music', 'theater', 'theater', 'film & video', 'theater', 'technology', 'music', 'technology', 'theater', 'music', 'music', 'music', 'publishing', 'film & video', 'theater', 'theater', 'film & video', 'theater', 'music', 'film & video', 'theater', 'theater', 'music', 'music', 'theater', 'film & video', 'music', 'film & video', 'music', 'journalism', 'food', 'theater', 'theater', 'music', 'film & video', 'music', 'theater', 'technology', 'games', 'film & video', 'technology', 'publishing', 'music', 'food', 'theater', 'film & video', 'publishing', 'games', 'theater', 'film & video', 'theater', 'theater', 'film & video', 'theater', 'music', 'film & video', 'food', 'technology', 'theater', 'theater', 'theater', 'publishing', 'music', 'food', 'music', 'film & video', 'theater', 'theater', 'music', 'theater', 'theater', 'theater', 'music', 'theater', 'publishing', 'theater', 'photography', 'theater', 'music', 'theater', 'photography', 'theater', 'theater', 'food', 'music', 'theater', 'theater', 'theater', 'theater', 'film & video', 'film & video', 'film & video', 'film & video', 'theater', 'theater', 'film & video', 'theater', 'theater', 'technology', 'theater', 'theater', 'music', 'games', 'publishing', 'food', 'theater', 'music', 'film & video', 'technology', 'technology', 'music', 'photography', 'food', 'film & video', 'music', 'film & video', 'theater', 'music', 'theater', 'theater', 'music', 'film & video', 'theater', 'journalism', 'theater', 'theater', 'music', 'theater', 'theater', 'music', 'photography', 'journalism', 'photography', 'publishing', 'film & video', 'food', 'games', 'theater', 'theater', 'theater', 'publishing', 'theater', 'technology', 'theater', 'film & video', 'technology', 'film & video', 'film & video', 'music', 'theater', 'theater', 'music', 'theater', 'music', 'technology', 'film & video', 'technology', 'theater', 'technology', 'publishing', 'film & video', 'publishing', 'technology', 'film & video', 'theater', 'theater', 'theater', 'theater', 'theater', 'publishing', 'music', 'games', 'theater', 'film & video', 'technology', 'publishing', 'theater', 'music', 'film & video', 'theater', 'theater', 'games', 'theater', 'technology', 'theater', 'film & video', 'technology', 'technology', 'music', 'music', 'theater', 'photography', 'publishing', 'music', 'theater', 'music', 'theater', 'theater', 'music', 'theater', 'theater', 'technology', 'technology', 'theater', 'film & video', 'technology', 'music', 'publishing', 'theater', 'photography', 'theater', 'theater', 'theater', 'film & video', 'music', 'music', 'games', 'music', 'music', 'theater', 'music', 'music', 'film & video', 'publishing', 'theater', 'games', 'theater', 'theater', 'music', 'theater', 'technology', 'music', 'theater', 'theater', 'film & video', 'theater', 'film & video', 'theater', 'film & video', 'music', 'technology', 'film & video', 'music', 'music', 'film & video', 'theater', 'theater', 'food', 'theater', 'publishing', 'music', 'film & video', 'games', 'technology', 'theater', 'theater', 'music', 'photography', 'photography', 'theater', 'music', 'film & video', 'film & video', 'theater', 'food', 'film & video', 'theater', 'games', 'publishing', 'games', 'music', 'music', 'theater', 'publishing', 'theater', 'games', 'music', 'film & video', 'music', 'music', 'publishing', 'film & video', 'theater', 'film & video', 'theater', 'theater', 'theater', 'photography', 'publishing', 'publishing', 'theater', 'technology', 'music', 'music', 'theater', 'film & video', 'theater', 'technology', 'technology', 'photography', 'film & video', 'technology', 'technology', 'food', 'film & video', 'music', 'music', 'music', 'games', 'music', 'publishing', 'theater', 'food', 'film & video', 'food', 'theater', 'technology', 'theater', 'theater', 'film & video', 'film & video', 'theater', 'photography', 'food', 'theater', 'film & video', 'theater', 'theater', 'film & video', 'photography', 'photography', 'music', 'photography', 'food', 'music', 'publishing', 'music', 'theater', 'theater', 'film & video', 'theater', 'theater', 'music', 'theater', 'theater', 'music', 'music', 'film & video', 'publishing', 'film & video', 'film & video', 'theater', 'food', 'theater', 'film & video', 'music', 'technology', 'music', 'technology', 'publishing', 'publishing', 'theater', 'film & video', 'theater', 'games', 'theater', 'theater', 'technology', 'film & video', 'film & video', 'theater', 'film & video', 'photography', 'film & video', 'publishing', 'theater', 'film & video', 'technology', 'music', 'theater', 'theater', 'theater', 'food', 'theater', 'technology', 'theater', 'theater', 'theater', 'music', 'theater', 'theater', 'theater', 'theater', 'film & video', 'publishing', 'games', 'technology', 'theater', 'theater', 'food', 'photography', 'photography', 'theater', 'theater', 'film & video', 'technology', 'theater', 'music', 'film & video', 'film & video', 'technology', 'theater', 'film & video', 'theater', 'film & video', 'publishing', 'technology', 'publishing', 'food', 'photography', 'theater', 'music', 'theater', 'music', 'food', 'theater', 'theater', 'film & video', 'technology', 'theater', 'music', 'theater', 'theater', 'food', 'games', 'theater', 'publishing', 'technology', 'film & video', 'film & video', 'theater', 'music', 'music', 'film & video', 'publishing', 'publishing', 'film & video', 'music', 'film & video', 'photography', 'publishing', 'food', 'theater', 'theater', 'music', 'food']

In [7]:
# Get the number of distinct values in the categories and subcategories lists.
categories = crowdfunding_info_df['Category'].unique()
subcategories = crowdfunding_info_df['Subcategory'].unique()

print(len(categories))
print(len(subcategories))

9
24

In [8]:
# Create numpy arrays from 1-9 for the categories and 1-24 for the subcategories.
category_ids = np.arange(1, 10)
subcategory_ids = np.arange(1, 25)

print(category_ids)
print(subcategory_ids)

[1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

In [9]:
# Use a list comprehension to add "cat" to each category_id. 
cat_ids = []



[cat_ids.append(f'cat{id}') for id in category_ids]

# Use a list comprehension to add "subcat" to each subcategory_id.    
scat_ids = []

[scat_ids.append(f'subcat{id}') for id in subcategory_ids] 
    
print(cat_ids)
print(scat_ids)

['cat1', 'cat2', 'cat3', 'cat4', 'cat5', 'cat6', 'cat7', 'cat8', 'cat9']
['subcat1', 'subcat2', 'subcat3', 'subcat4', 'subcat5', 'subcat6', 'subcat7', 'subcat8', 'subcat9', 'subcat10', 'subcat11', 'subcat12', 'subcat13', 'subcat14', 'subcat15', 'subcat16', 'subcat17', 'subcat18', 'subcat19', 'subcat20', 'subcat21', 'subcat22', 'subcat23', 'subcat24']

In [10]:
# Create a category DataFrame with the category_id array as the category_id and categories list as the category name.
category_df = pd.DataFrame(list(zip(cat_ids, categories)), columns = ['category_id', 'category'])
# Create a category DataFrame with the subcategory_id array as the subcategory_id and subcategories list as the subcategory name. 
subcategory_df = pd.DataFrame(list(zip(scat_ids, subcategories)), columns = ['subcategory_id', 'subcategory'])

In [11]:
category_df

  category_id      category
0        cat1          food
1        cat2         music
2        cat3    technology
3        cat4       theater
4        cat5  film & video
5        cat6    publishing
6        cat7         games
7        cat8   photography
8        cat9    journalism

In [12]:
subcategory_df

   subcategory_id        subcategory
0         subcat1        food trucks
1         subcat2               rock
2         subcat3                web
3         subcat4              plays
4         subcat5        documentary
5         subcat6     electric music
6         subcat7              drama
7         subcat8         indie rock
8         subcat9          wearables
9        subcat10         nonfiction
10       subcat11          animation
11       subcat12        video games
12       subcat13             shorts
13       subcat14            fiction
14       subcat15  photography books
15       subcat16   radio & podcasts
16       subcat17              metal
17       subcat18               jazz
18       subcat19       translations
19       subcat20         television
20       subcat21       mobile games
21       subcat22        world music
22       subcat23    science fiction
23       subcat24              audio

In [13]:
# Export categories_df and subcategories_df as CSV files.
category_df.to_csv("Resources/category.csv", index=False)

subcategory_df.to_csv("Resources/subcategory.csv", index=False)

### Campaign DataFrame
----
**Create a Campaign DataFrame that has the following columns:**
- The "cf_id" column.
- The "contact_id" column.
- The “company_name” column.
- The "blurb" column is renamed as "description."
- The "goal" column.
- The "goal" column is converted to a `float` datatype.
- The "pledged" column is converted to a `float` datatype. 
- The "backers_count" column. 
- The "country" column.
- The "currency" column.
- The "launched_at" column is renamed as "launch_date" and converted to a datetime format. 
- The "deadline" column is renamed as "end_date" and converted to a datetime format.
- The "category_id" with the unique number matching the “category_id” from the category DataFrame. 
- The "subcategory_id" with the unique number matching the “subcategory_id” from the subcategory DataFrame.
- And, create a column that contains the unique four-digit contact ID number from the `contact.xlsx` file.
 

Then export the DataFrame as a `campaign.csv` CSV file.

In [14]:
# Create a copy of the crowdfunding_info_df DataFrame name campaign_df. 
campaign_df = crowdfunding_info_df.copy()
campaign_df.head()

,cf_id,contact_id,company_name,blurb,goal,pledged,outcome,backers_count,country,currency,launched_at,deadline,staff_pick,spotlight,category & sub-category,Category,Subcategory
0,147,4661,"Baldwin, Riley and Jackson",Pre-emptive tertiary standardization,100,0,failed,0,CA,CAD,1581573600,1614578400,False,False,food/food trucks,food,food trucks
1,1621,3765,Odom Inc,Managed bottom-line architecture,1400,14560,successful,158,US,USD,1611554400,1621918800,False,True,music/rock,music,rock
2,1812,4187,"Melton, Robinson and Fritz",Function-based leadingedge pricing structure,108400,142523,successful,1425,AU,AUD,1608184800,1640844000,False,False,technology/web,technology,web
3,2156,4941,"Mcdonald, Gonzalez and Ross",Vision-oriented fresh-thinking conglomeration,4200,2477,failed,24,US,USD,1634792400,1642399200,False,False,music/rock,music,rock
4,1365,2199,Larson-Little,Proactive foreground core,7600,5265,failed,53,US,USD,1608530400,1629694800,False,False,theater/plays,theater,plays

In [15]:
# Rename the blurb, launched_at, and deadline columns
campaign_df=campaign_df.rename(columns={"blurb":"description", "launched_at": "launch_date",  "deadline": "end_date"})
campaign_df

,cf_id,contact_id,company_name,description,goal,pledged,outcome,backers_count,country,currency,launch_date,end_date,staff_pick,spotlight,category & sub-category,Category,Subcategory
0,147,4661,"Baldwin, Riley and Jackson",Pre-emptive tertiary standardization,100,0,failed,0,CA,CAD,1581573600,1614578400,False,False,food/food trucks,food,food trucks
1,1621,3765,Odom Inc,Managed bottom-line architecture,1400,14560,successful,158,US,USD,1611554400,1621918800,False,True,music/rock,music,rock
2,1812,4187,"Melton, Robinson and Fritz",Function-based leadingedge pricing structure,108400,142523,successful,1425,AU,AUD,1608184800,1640844000,False,False,technology/web,technology,web
3,2156,4941,"Mcdonald, Gonzalez and Ross",Vision-oriented fresh-thinking conglomeration,4200,2477,failed,24,US,USD,1634792400,1642399200,False,False,music/rock,music,rock
4,1365,2199,Larson-Little,Proactive foreground core,7600,5265,failed,53,US,USD,1608530400,1629694800,False,False,theater/plays,theater,plays
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2986,3684,Manning-Hamilton,Vision-oriented scalable definition,97300,153216,successful,2043,US,USD,1609221600,1622350800,False,True,food/food trucks,food,food trucks
996,2031,5784,Butler LLC,Future-proofed upward-trending migration,6600,4814,failed,112,US,USD,1634274000,1638252000,False,False,theater/plays,theater,plays
997,1627,1498,Ball LLC,Right-sized full-range throughput,7600,4603,canceled,139,IT,EUR,1636174800,1639116000,False,False,theater/plays,theater,plays
998,2175,6073,"Taylor, Santiago and Flores",Polarized composite customer loyalty,66600,37823,failed,374,US,USD,1602133200,1618117200,False,True,music/indie rock,music,indie rock
999,1788,4939,"Hernandez, Norton and Kelley",Expanded eco-centric policy,111100,62819,canceled,1122,US,USD,1609308000,1629262800,False,False,food/food trucks,food,food trucks

In [16]:
# Convert the goal and pledged columns to a `float` data type.
campaign_df = campaign_df.astype({'goal':'float','pledged':'float'})

In [17]:
# Check the datatypes
campaign_df.dtypes

cf_id                        int64
contact_id                   int64
company_name                object
description                 object
goal                       float64
pledged                    float64
outcome                     object
backers_count                int64
country                     object
currency                    object
launch_date                  int64
end_date                     int64
staff_pick                    bool
spotlight                     bool
category & sub-category     object
Category                    object
Subcategory                 object
dtype: object

In [18]:
launch = list(campaign_df['launch_date'])
end = list(campaign_df['end_date'])

In [19]:
from datetime import datetime
launch_date = []
end_date = []

for l in launch:
    launch_date.append((datetime.fromtimestamp(l).strftime("%m-%d-%Y")))

for e in end:
    end_date.append((datetime.fromtimestamp(e).strftime("%m-%d-%Y")))
    
df = pd.DataFrame (launch_date, columns = ['launch_Date'])
df2 = pd.DataFrame (end_date, columns = ['end_Date'])

time_df = pd.merge(df, df2, left_index=True, right_index=True)

In [20]:
# Format the launched_date and end_date columns to datetime format


# campaign_df['launch_date'] = pd.to_datetime(campaign_df['launch_date'], format="%m-%d-%Y")

# campaign_df['launch_date']= pd.to_datetime(campaign_df['launch_date'])
# campaign_df['end_date']= pd.to_datetime(campaign_df['end_date'])
campaign_df = campaign_df.drop(columns=['launch_date','end_date'])
campaign_df = pd.merge(campaign_df, time_df, left_index=True, right_index=True)

In [21]:
# Merge the campaign_df with the category_df on the "category" column and 
# the subcategory_df on the "subcategory" column.
campaign_merged_df = pd.merge(campaign_df, category_df, how="left", left_on="Category", right_on='category')
campaign_merged_df = pd.merge(campaign_merged_df, subcategory_df, how="left", left_on="Subcategory", right_on='subcategory')

campaign_merged_df.columns

Index(['cf_id', 'contact_id', 'company_name', 'description', 'goal', 'pledged',
       'outcome', 'backers_count', 'country', 'currency', 'staff_pick',
       'spotlight', 'category & sub-category', 'Category', 'Subcategory',
       'launch_Date', 'end_Date', 'category_id', 'category', 'subcategory_id',
       'subcategory'],
      dtype='object')

In [22]:
# Drop unwanted columns
campaign_merged_df = campaign_merged_df.drop(columns=['Category', 'Subcategory', 'staff_pick', 'spotlight', 'category & sub-category', 'category', 'subcategory'])

In [23]:
campaign_cleaned = campaign_merged_df
campaign_cleaned

,cf_id,contact_id,company_name,description,goal,pledged,outcome,backers_count,country,currency,launch_Date,end_Date,category_id,subcategory_id
0,147,4661,"Baldwin, Riley and Jackson",Pre-emptive tertiary standardization,100.0,0.0,failed,0,CA,CAD,02-13-2020,03-01-2021,cat1,subcat1
1,1621,3765,Odom Inc,Managed bottom-line architecture,1400.0,14560.0,successful,158,US,USD,01-25-2021,05-25-2021,cat2,subcat2
2,1812,4187,"Melton, Robinson and Fritz",Function-based leadingedge pricing structure,108400.0,142523.0,successful,1425,AU,AUD,12-17-2020,12-30-2021,cat3,subcat3
3,2156,4941,"Mcdonald, Gonzalez and Ross",Vision-oriented fresh-thinking conglomeration,4200.0,2477.0,failed,24,US,USD,10-21-2021,01-17-2022,cat2,subcat2
4,1365,2199,Larson-Little,Proactive foreground core,7600.0,5265.0,failed,53,US,USD,12-21-2020,08-23-2021,cat4,subcat4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2986,3684,Manning-Hamilton,Vision-oriented scalable definition,97300.0,153216.0,successful,2043,US,USD,12-29-2020,05-30-2021,cat1,subcat1
996,2031,5784,Butler LLC,Future-proofed upward-trending migration,6600.0,4814.0,failed,112,US,USD,10-15-2021,11-30-2021,cat4,subcat4
997,1627,1498,Ball LLC,Right-sized full-range throughput,7600.0,4603.0,canceled,139,IT,EUR,11-06-2021,12-10-2021,cat4,subcat4
998,2175,6073,"Taylor, Santiago and Flores",Polarized composite customer loyalty,66600.0,37823.0,failed,374,US,USD,10-08-2020,04-11-2021,cat2,subcat8
999,1788,4939,"Hernandez, Norton and Kelley",Expanded eco-centric policy,111100.0,62819.0,canceled,1122,US,USD,12-30-2020,08-18-2021,cat1,subcat1

In [24]:
# Export the DataFrame as a CSV file. 
campaign_cleaned.to_csv("Resources/campaign.csv", index=False)

### Extract the contacts.xlsx Data.

In [61]:
import pandas as pd
# Read the data into a Pandas DataFrame. Use the `header=2` parameter when reading in the data.
contact_info_df = pd.read_excel('Resources/contacts.xlsx', header=3)
contact_info_df.head()

                                        contact_info
0  {"contact_id": 4661, "name": "Cecilia Velasco"...
1  {"contact_id": 3765, "name": "Mariana Ellis", ...
2  {"contact_id": 4187, "name": "Sofie Woods", "e...
3  {"contact_id": 4941, "name": "Jeanette Iannott...
4  {"contact_id": 2199, "name": "Samuel Sorgatz",...

### Create the Contacts DataFrame 
---
**Create a Contacts DataFrame that has the following columns:**
- A column named "contact_id"  that contains the unique number of the contact person.
- A column named "first_name" that contains the first name of the contact person.
- A column named "last_name" that contains the first name of the contact person.
- A column named "email" that contains the email address of the contact person

Then export the DataFrame as a `contacts.csv` CSV file.

### Option 1: Use Pandas to create the contacts DataFrame.

In [62]:
# Iterate through the contact_info_df and convert each row to a dictionary.
import json
dict_values = []

contact_list = contact_info_df.values.tolist()

for contact in contact_list:
    dict_values.append(contact[0].split(","))
    
    
# Print out the list of values for each row.
# print(dict_values)

In [63]:
contacts_df = pd.DataFrame(dict_values, columns=['contact_id', 'name', 'email'])
contacts_df['contact_id'] = contacts_df['contact_id'].replace({'{"contact_id": ': ''}, regex=True)

contacts_df['name']= contacts_df['name'].replace({'"': ''}, regex=True)
contacts_df['name'] = contacts_df['name'].replace({' name: ': ''}, regex=True)
contacts_df['email'] = contacts_df['email'].replace({' "email": "': ''}, regex=True)
contacts_df['email'] = contacts_df['email'].replace({'"': ''}, regex=True)
contacts_df['email'] = contacts_df['email'].replace({'}': ''}, regex=True)

In [64]:
# Create a contact_info DataFrame and add each list of values, i.e., each row 
# to the 'contact_id', 'name', 'email' columns.
contacts_df

,contact_id,name,email
0,4661,Cecilia Velasco,cecilia.velasco@rodrigues.fr
1,3765,Mariana Ellis,mariana.ellis@rossi.org
2,4187,Sofie Woods,sofie.woods@riviere.com
3,4941,Jeanette Iannotti,jeanette.iannotti@yahoo.com
4,2199,Samuel Sorgatz,samuel.sorgatz@gmail.com
...,...,...,...
995,3684,Whitney Noack,whitney.noack@laboratorios.org
996,5784,Gelsomina Migliaccio,gelsomina.migliaccio@junk.com
997,1498,Evangelista Pereira,evangelista.pereira@thompson-peterson.biz
998,6073,Gareth Comolli,gareth.comolli@tiscali.fr
999,4939,Michelangelo Hess,michelangelo.hess@bouygtel.fr

In [65]:
# Check the datatypes.

In [66]:
# Create a "first"name" and "last_name" column with the first and last names from the "name" column. 
contacts_df[['first_name', 'last_name']] = contacts_df['name'].str.split(' ', 1, expand=True)



# Drop the contact_name column
contacts_df = contacts_df.drop(columns=['name'])

In [74]:
#contact_id to integer
contacts_df['contact_id'] = contacts_df['contact_id'].astype(int)

In [75]:
# Reorder the columns
neworder = ['contact_id', 'first_name', 'last_name', 'email', ]
contacts_df_clean = contacts_df.reindex(columns=neworder)

In [76]:
# Check the datatypes one more time before exporting as CSV file.
contacts_df_clean.dtypes

contact_id     int64
first_name    object
last_name     object
email         object
dtype: object

In [77]:
# Export the DataFrame as a CSV file. 
contacts_df_clean.to_csv("Resources/contacts.csv", encoding='utf8', index=False)

### Option 2: Use regex to create the contacts DataFrame.

In [ ]:
contact_info_df_copy = contact_info_df.copy()
contact_info_df_copy.head()

In [ ]:
# Extract the four-digit contact ID number.

In [ ]:
# Check the datatypes.

In [ ]:
# Convert the "contact_id" column to an int64 data type.

In [ ]:
# Extract the name of the contact and add it to a new column.

In [ ]:
# Extract the email from the contacts and add the values to a new column.

In [ ]:
# Create a copy of the contact_info_df with the 'contact_id', 'name', 'email' columns.

In [ ]:
# Create a "first"name" and "last_name" column with the first and last names from the "name" column. 


# Drop the contact_name column

In [ ]:
# Reorder the columns

In [ ]:
# Check the datatypes one more time before exporting as CSV file.

In [ ]:
# Export the DataFrame as a CSV file. 
# contacts_df_clean.to_csv("Resources/contacts.csv", encoding='utf8', index=False)